services:
  backend:
    image: f3rym/eto-backend
    env_file: backend/.env
    ports:
      - 8000:8000
    networks:
      - f3Net
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8000/api/healthcheck"]
      interval: 5s 
      timeout: 10s
      retries: 3
      start_period: 3s
  frontend:
    image: f3rym/eto-frontend
    env_file: frontend/.env
    restart: always
    ports:
      - 80:80
    networks:
      - f3Net
    depends_on:
      backend:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    restart: unless-stopped 
    networks:
      - f3Net 
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10
networks:
  f3Net:
    driver: bridge
volumes:
  postgres: