apiVersion: v1
kind: Secret
metadata:
  name: config-secret
  namespace: app

type: Opaque
data:
  postgres-password: cGFzc3dvcmQ=
  postgres-user: ZXRvYXBw
  postgres-db: ZXRvYXBw
  postgres-host: ZGI=