name: Build
on:
  push:
    branches:
      - main
  # workflow_dispatch:
  # release:
  #   types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy: 
      matrix:
        image: 
          - backend
          - frontend
    steps:
      - name: copy-repo
        uses: actions/checkout@v3
      - name: .env_backend
        run: |
          if [[ ! -f ./${{ matrix.image }}/.env ]]; then
            mv ./${{ matrix.image }}/.env.example ./${{ matrix.image }}/.env
          fi
#docker        
      - name: buildx
        uses: docker/setup-buildx-action@v3
      - name: qemu
        uses: docker/setup-qemu-action@v3
    
      - name: login to dockerHub
        uses: docker/login-action@v3
        with:
          username: f3rym
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build + push
        uses: docker/build-push-action@v6
        with: 
          context: ./${{ matrix.image }}
          file: Dockerfile
          push: true
          tags: |
            f3rym/eto-${{ matrix.image }}:latest
            f3rym/eto-${{ matrix.image }}:${{ github.sha }}
